services:
  mongo:
    # Arm64 Architecture
    image: arm64v8/mongo:7
    # image: mongo:7 for x86_64 Architecture
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: