version: '3.9'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repo_development
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data:
